### PR TITLE
Responsiveness Fixed

### PR DESCRIPTION
**Pull request by inkerton**
This is in response to the issue #106

### CODE REVIEW

**Comment by notsoocool** [comment]
there is no file change @inkerton XD

**Comment by inkerton** [comment]
I will open another PR.

**Comment by inkerton** [comment]
You already accepted the changes in this PR #107 

My original PR was #60  You can check out the file changes here You closed the PR but I worked On top of that branch so the changes Remained. Please accept this empty PR so I can get points. 

Check out the original changes from here 
[https://github.com/notsoocool/codecache/pull/60/files](https://github.com/notsoocool/codecache/pull/60/files)

and checkout the current code they are already present. @notsoocool 

If you had just accepted my PR then or atleast let the person know before you close their PR so they can revert the changes they made. Closing the Pr doesnot mean that changes are erased. Checkout the original changes and give me points on this PR please.

**Comment by notsoocool** [comment]
@inkerton I understand your concern, but please note that when a PR is closed, it’s because it either didn’t meet the contributing guidelines or wasn’t tied to an assigned issue. It's a general rule to first get assigned to an issue before working on it, which helps in avoiding any conflicts and ensures we’re all on the same page.

Closing the PR does mean that any unmerged changes will be disregarded, especially when someone fetches the latest changes from the repo. That’s the reason we stress on keeping the workflow organized by opening issues and getting assigned. Once the latest changes are fetched, any unmerged changes become outdated or irrelevant. 

Regarding the #107 PR, I reviewed the responsiveness changes and found that the only required issue was solved, with no substantial improvements made to responsiveness. What I can do is reopen your original PR (#60), and you can fetch the latest changes, resolve any conflicts, and push your updates. This way, we can proceed smoothly without any further confusion.

Let me know how you would like to proceed.

**Comment by notsoocool** [comment]
@inkerton 
I will wait for your response till Monday Evening and then i will close your PR.

**Comment by inkerton** [comment]
You can close the PR if I am not getting points for this one. I don't see any other issue I want to contribute to right now. Feel free to do as you please.

**Pull request closed without merging**
