### PR TITLE
added copyright section

### PR DESCRIPTION
**Pull request by ABHISIKTAcommits**
ISSUE #98 solved
SO THE WEBSITE LOOKS LIKE :

Screenshot 2024-10-15 163925

### CODE REVIEW

**Comment by notsoocool** [comment]
@ABHISIKTAcommits, please don't add a new line for the copyright section. Kindly continue it in the existing line to keep the footer layout consistent. Thanks!

**Comment by ABHISIKTAcommits** [comment]
@notsoocool done with the work...
now website looks as :

Screenshot 2024-10-16 092313

**Comment by ABHISIKTAcommits** [comment]
Closed #101

**Comment by notsoocool** [comment]
@ABHISIKTAcommits, 

Could you please create separate pull requests (PRs) for each assigned issue? Additionally, make sure to push your changes to the `develop` branch after fetching the latest updates. 

Thank you!

**Pull request closed without merging**
