### PR TITLE
fix #27: migration to prisma orm and optimizations

### LINKED ISSUE #27: Integrate Prisma ORM to Replace MongoDB Usage (TESTING)
Using raw MongoDB increases complexity in the project. We will integrate Prisma ORM to simplify database interactions and improve maintainability. The following steps will be taken:

- Replace current MongoDB models and queries with Prisma models and queries.
- Update all API routes to use Prisma.
- Ensure that the existing functionalities (e.g., snippets, ratings, user permissions) work seamlessly after the migration.
Assignee: @priyanshuverma-dev
Branch: Use the newly created branch for this issue and raise a PR once completed.

### PR DESCRIPTION
**Pull request by priyanshuverma-dev**
### Changes and improvements

- All native mongodb is migrated to prisma
- All mongodb functions are marked depreciated. it can be removed after successful deploy.
- **Database Changes**:
 -  `snippetRequestModel` is removed and placed a new field in `snippetModel` named `status` which determines 
    - `APPROVED`
    - `PENDING`
    - `REJECTED` 
 - `averageRating` is added in `snippetModel` and updated accordingly for better outcomes.

### CODE REVIEW

**Comment by notsoocool** [comment]
Hey @priyanshuverma-dev , the changes you've made look good, but it's better not to combine both the `snippetModel` and `snippetRequestModel` into one. Keeping them separate makes it easier to track the database requests and manage the workflow. Have you tested locally by adding, accepting, rejecting, and displaying all the snippets? Also, there's no need to modify the `README` file, and `.env` shouldn't be included in `.gitignore`; we use `.env.local` specifically for that purpose.

**Comment by priyanshuverma-dev** [comment]
- Hello @notsoocool, I have tested the integration locally and everything is working file
- I have changed `.env.local` to `.env` because `prisma` uses that by default. If you want to use `.env.local` then needs to install separate `dotenv-cli` [package](https://www.npmjs.com/package/dotenv-cli)  for that.
- Lastly Should I change separate model for snippet request then:
  - what field should be their or same as previous.

**Update me if want to make about anything then I will start working accordingly**

**Comment by notsoocool** [comment]
Hey @priyanshuverma-dev, thanks for the update! 

Regarding the `.env.local`, I prefer sticking with it for now since it keeps our environment variables more secure and local to each developer. If Prisma requires the `.env` file by default, you can just install the `dotenv-cli` package, as you mentioned, to handle it.

For the `snippetRequest` model, please keep it separate from the main snippet model. The fields should remain the same as they were previously: `title`, `language`, `code`, `description`, `tags`, `category`, `difficulty`, `usage`, and `submittedBy`.

Let me know once these changes are made, and feel free to reach out if anything is unclear!

**Comment by priyanshuverma-dev** [comment]
@notsoocool Got your points will update shortly 👍.

**Comment by notsoocool** [comment]
> Hey @priyanshuverma-dev, thanks for the update!
> 
> Regarding the `.env.local`, I prefer sticking with it for now since it keeps our environment variables more secure and local to each developer. If Prisma requires the `.env` file by default, you can just install the `dotenv-cli` package, as you mentioned, to handle it.
> 
> For the `snippetRequest` model, please keep it separate from the main snippet model. The fields should remain the same as they were previously: `title`, `language`, `code`, `description`, `tags`, `category`, `difficulty`, `usage`, and `submittedBy`.
> 
> Let me know once these changes are made, and feel free to reach out if anything is unclear!

Once these changes are made, please push them to the `27-integrate-prisma-orm` branch.

**Comment by priyanshuverma-dev** [comment]
### Changes and improvements

- All native mongodb is migrated to prisma
- All mongodb functions are marked depreciated. it can be removed after successful deploy.
 - `averageRating` is added in `snippetModel` and updated accordingly for better outcomes.

### Things to know

- To use prisma for generation and migrations. You need to use `dotenv-cli` to work with `.env.local`
- like example
```bash
dotenv -e .env.local -- npx prisma db push
```
For more information about env see official [docs](https://www.prisma.io/docs/orm/more/development-environment/environment-variables/managing-env-files-and-setting-variables).

**Comment by priyanshuverma-dev** [comment]
> @notsoocool 
> Once these changes are made, please push them to the `27-integrate-prisma-orm` branch.


Should I create a new PR to point that to the `27-integrate-prisma-orm` branch.

**Comment by notsoocool** [comment]
@priyanshuverma-dev thank you for the update and improvements! I appreciate the migration to Prisma and the changes to `snippetModel`. I’ll review the code once I get some time, and then I’ll merge the PR to the `27-integrate-prisma-orm` branch

**Comment by notsoocool** [comment]
> > @notsoocool
> > Once these changes are made, please push them to the `27-integrate-prisma-orm` branch.
> 
> Should I create a new PR to point that to the `27-integrate-prisma-orm` branch.

i will do it, no worries

**Comment by notsoocool** [comment]
@priyanshuverma-dev actually you have pulled changes from `main` branch instead of the `develop` or `27-integrate-prisma-orm` branch kindly pull changes from `develop` or `27-integrate-prisma-orm` branch and then make a PR for `27-integrate-prisma-orm`

**Comment by priyanshuverma-dev** [comment]
@notsoocool  Should i create a new PR pointing `develop` branch

**Comment by priyanshuverma-dev** [comment]
@notsoocool I think I fixed the collateral damage. Let me know If anything else is required.

**Comment by notsoocool** [comment]
Hey @priyanshuverma-dev, thank you so much for integrating Prisma ORM into our project! Your contribution is greatly appreciated, and it's going to simplify things a lot moving forward. Whenever you're free, I’d love your help with setting up the project as well with new Prisma Integration. Let me know what time works for you!

**Pull request merged**
