### PR TITLE
feat(AddSnippet): Refactor component for better UX and maintainability

### LINKED ISSUE #136: Refactor Add-Snippet Component for Improved UX and Maintainability
Is your feature request related to a problem?
Yes, the current AddSnippet component lacks efficient state management, resulting in code duplication and poor user feedback.

Describe the solution you'd like:
- Consolidate form state management into a single object.
- Implement a reusable `FormField` component to reduce duplication.
- Improve form validation with specific feedback and add a loading state to prevent multiple submissions.
- Enhance accessibility by linking labels properly and optimize performance using `useCallback`.

Describe alternatives you've considered:
Small incremental updates to the existing component, but a full refactor offers greater long-term benefits.

Additional context:
This refactor will improve maintainability, align with React best practices, and enhance the overall user experience.

### PR DESCRIPTION
**Pull request by yuvraj1107thapa**
This PR refactors the AddSnippet component to improve user experience and code maintainability.

Changes:
- Consolidate form state management
- Implement reusable FormField component
- Enhance form validation and error handling
- Add loading state to prevent multiple submissions

Impact:
- Improved user experience with better feedback
- Enhanced code maintainability and readability
- Reduced complexity and code duplication

Testing:
- Verified all form fields work with new state management
- Tested form submission with valid and invalid inputs
- Ensured error messages display correctly
- Checked loading state prevents multiple submissions

No breaking changes.

### CODE REVIEW

**Comment by notsoocool** [comment]
Here’s an improved version of your response:

Hi @yuvraj1107thapa,

I appreciate your contribution and the effort you put into this PR. However, before raising a PR, we have certain rules and a code of conduct that need to be followed. You should first be assigned to an issue, then proceed to raise a PR.

Kindly create an issue describing the changes, and once that's done, I will review the code and assign the appropriate labels.

Thanks for understanding!

**Comment by notsoocool** [comment]
@yuvraj1107thapa still its getting failed why deploying

**Comment by notsoocool** [comment]
@yuvraj1107thapa if you didn't fix it by today itself, I will close your PR

**Comment by yuvraj1107thapa** [comment]
@notsoocool Fixed all deployment issues and improved component stability. The code has been tested locally and is working as expected. It is ready for review.

**Comment by notsoocool** [comment]
Sorry for the delayed review, @yuvraj1107thapa. I was about to merge your PR, but I noticed an issue: when clicking "Add Snippets," it only gives a toast notification for "usage cannot be empty," even if all fields are empty. Ideally, it should validate each field in order, starting with the title and then moving to the others. Could you please address this?

**Review by notsoocool — CHANGES_REQUESTED** [review]
Solve it, and test it locally and then i will merge your PR

**Comment by notsoocool** [comment]
@yuvraj1107thapa any updates??

**Pull request closed without merging**
