### PR TITLE
Delete Snippet Completed

### PR DESCRIPTION
**Pull request by inkerton**
image

### CODE REVIEW

**Comment by inkerton** [comment]
This is in response to the issue #74 
@notsoocool Review the PR and merge it

**Comment by notsoocool** [comment]
Instead of directly deleting a snippet, I propose implementing a request deletion option. If a user wishes to delete a snippet, they should provide a reason for the deletion. This reason will be displayed on the admin page alongside the snippet. The admin will then have the authority to approve or reject the delete request. If the admin approves the request, the snippet will be deleted from the system.

**Comment by inkerton** [comment]
Then shall I make a **DeleteRequest** model also with a reason from the user to delete it and then store in the deleteRequest collection. Also **I don't have admin access** so I won't be able to do much on that part till u tell me how to access the admin panel.

Also since **I will be making a whole new model and request setup I would like the issue to be raised to level3.** I will start working on the model and I was thinking of a **Dialogue box** that will open up on delete where the user can enter the delete request along with the reason.

**Comment by notsoocool** [comment]
> Then shall I make a **DeleteRequest** model also with a reason from the user to delete it and then store in the deleteRequest collection. Also **I don't have admin access** so I won't be able to do much on that part till u tell me how to access the admin panel.
> 
> Also since **I will be making a whole new model and request setup I would like the issue to be raised to level3.** I will start working on the model and I was thinking of a **Dialogue box** that will open up on delete where the user can enter the delete request along with the reason.
> 
> @notsoocool

Hey, this looks perfect! You can go ahead with the implementation. For admin access, you have an environment variable named `ADMIN_USER_IDS` in the `.env.sample` file. Just add your user ID (which you can get from Clerk) and save it, and you'll have admin access.

Also, for labeling issues or PRs, don’t worry—I’ll label you appropriately based on the work. I won't show any bias to anyone 😊.

**Comment by inkerton** [comment]
created the delepteRequest Model 
image

**Comment by notsoocool** [comment]
> created the delepteRequest Model image

just a suggestion no need to have so many field, just have the user id, description, snippet id, thats it

**Comment by inkerton** [comment]
ok this is how I need to add my user id 
ADMIN_USER_IDS=user_2iwz8k1oy36JHoZHpUeJC2X8MzK

in the .env.local but i still can't see the Admin panel @notsoocool

**Comment by inkerton** [comment]
image

Changed the Model @notsoocool

**Comment by inkerton** [comment]
image

**Comment by inkerton** [comment]
image

**Comment by inkerton** [comment]
**Tabs for easy admin navigation** 
image

----------------------------------------------------------------------------------------------------------------------------------------


**Table with delete Requests data and Accept and Reject row actions**
image


I have completed my work. Since the whole process has been completed please check out the PR merge it and raise the level to level3. @notsoocool

**Comment by inkerton** [comment]
I added these following

1. Delete button
2. Button modal open 
3. Delete request model (revised according to your request)
4. backend api/getdeleteRequest to fetch all requests
5. tabs for easy admin navigation (rerendered the whole page)
6. Delete requests table
7. added table actions -'Accept' and 'Reject'
8. api call for api/getdeleteRequest/accept
9. api call for api/getdeleteRequest/reject
10. working logic for all 

Screenshots added above 
@notsoocool

**Comment by inkerton** [comment]
@notsoocool Have you checked my PR. Please merge it and add level3 tag also.

**Comment by inkerton** [comment]
Is there any issue with the PR ???

@notsoocool  If not thehn please do merge it i need to work on the edit snippet too that I will build upon this one.

**Comment by notsoocool** [comment]
> @notsoocool Have you checked my PR. Please merge it and add level3 tag also.

Just a friendly reminder—please avoid mentioning what to label your PR. This is your second reminder, so I kindly ask you to keep this in mind moving forward. Thank you for understanding!

**Comment by notsoocool** [comment]
@inkerton I’ve tested your code locally, and everything works smoothly until I reach the snippet deletion page. The issue arises when I attempt to delete a snippet—it doesn’t get removed from the database. Could you please take a look and see if anything might be causing this?

**Comment by notsoocool** [comment]
Also i need you add some toast notification and also need to improve the UI for level3 label, but before that solve the above mentioned problem

**Comment by inkerton** [comment]
image

@notsoocool

**Comment by inkerton** [comment]
What UI changes do you want?? Specify please @notsoocool

**Comment by notsoocool** [comment]
This would be some last Checks you have to complete and you are good to go.

**Comment by inkerton** [comment]
Their was no snippet rating being displayed in the first place @notsoocool 
image


image



image


Refer to the original PR #50

**Comment by inkerton** [comment]
@notsoocool  As for the dynamic removal of table row . it is done.

**Comment by notsoocool** [comment]
Hi @inkerton,

Could you please fetch the latest changes from the develop branch and test it? The rated snippet section is functioning properly there.

Thank you!

**Comment by inkerton** [comment]
@notsoocool you can Merge PR now

**Review by notsoocool — APPROVED** [review]
Perfect @inkerton

**Pull request merged**
