### PR TITLE
Added footer

### LINKED ISSUE #85: Missing Footer in Website Design
# Missing Footer in Website Design

## Expected Behavior
- The website should have a footer to provide additional information, navigation links, and contact details, which enhances the user experience.

## Current Behavior
- The website currently lacks a footer, which may lead to a lack of information and navigation options at the bottom of the page.

## Steps to Reproduce
1. Open the web application.
2. Scroll to the bottom of any page.
3. Observe that there is no footer present.

## Screenshots
 
footer

## Possible Solutions
- Implement a footer that includes essential links, copyright information, and contact details.
- Consider adding social media links and a newsletter signup form for better user engagement.

## Environment
- **Browser**: [129.0.6668.1001 ]
- **Operating System**: [Windows 11]

## Additional Context
- A footer is a standard element in web design, providing users with essential information and a means to navigate back to key sections of the site.
- Adding a footer can also improve SEO by including additional links and keywords.

## Labels
- Feature Request
- UI/UX
- gssoc-ext
- level 1
- hacktoberfest-accepted

### PR DESCRIPTION
**Pull request by Gauravtb2253**
I have added the footer pls check it

Issue #85

### CODE REVIEW

**Comment by notsoocool** [comment]
Sorry @Gauravtb2253, for now I don't feel like adding the footer as it’s totally changing our design and it’s not looking good to me. If you want, just tweak it a little bit—add a separator between the existing footer and the new footer, and don’t change the format of the existing footer. Also, use a light font for the new footer. If I like it, then I will merge it into production; otherwise, I’ll keep it in the review branch after merging. That will at least gain you some points for your contribution, but first, do the things I mentioned.

**Comment by Gauravtb2253** [comment]
> Sorry @Gauravtb2253, for now I don't feel like adding the footer as it’s totally changing our design and it’s not looking good to me. If you want, just tweak it a little bit—add a separator between the existing footer and the new footer, and don’t change the format of the existing footer. Also, use a light font for the new footer. If I like it, then I will merge it into production; otherwise, I’ll keep it in the review branch after merging. That will at least gain you some points for your contribution, but first, do the things I mentioned.

Yes I will change it

**Comment by Gauravtb2253** [comment]
pls check it

**Comment by Gauravtb2253** [comment]
thank you !!

**Comment by Gauravtb2253** [comment]
Do you have more issues for solving

**Comment by notsoocool** [comment]
> Do you have more issues for solving

You just give me 10 min i am dealing with some issue now, as soon as i am free i will tel you, until go through all the issue and check whatever issues you are comfortable with

**Comment by notsoocool** [comment]
Thank you for your contribution! If you'd like to further support the project, feel free to star the repository—it helps the project reach more people and grow.

**Comment by notsoocool** [comment]
@Gauravtb2253 if you dont mind can you do any of the pinned issues

**Comment by Gauravtb2253** [comment]
I would like to work on the chatbot feature
Just can you explain what exactly is needed

**Comment by notsoocool** [comment]
> I would like to work on the chatbot feature Just can you explain what exactly is needed

Sure, just comment on that issue and i will explain

**Pull request merged**
