### PR TITLE
Added the contributors page with sleek ui and dynamic functionality.

### PR DESCRIPTION
**Pull request by tarunkumar2005**
Added the contributors page with sleek ui and dynamic functionality.

closes :- #83 

image

https://github.com/user-attachments/assets/a55dc3cd-1e61-4149-9a5b-f187423667a5

@notsoocool Please check this PR, if you find any issue or you want any changes please mention me i will do those changes otherwise if all is fine you can merge this and assign this to me and put relevant labels such as gssoc 2024 ext, hacktoberfest and level. 
i think it can be level 3 because the page is very important in open source to showcase the efforts of the people contributing in building it and it is not static it is dynamic as a new contributor is added to your repo it will be automatically added there so this is the beauty of this. (Just my suggestion all is upto you how you see my work.)

### CODE REVIEW

**Comment by notsoocool** [comment]
@tarunkumar2005 
Why is the contributors page only showing 5 contributors when there are actually 11? Could you check if there's a limit or issue with the display logic?

**Comment by tarunkumar2005** [comment]
@notsoocool I can't say about this the api is giving only 5 objects in the response. I tried to check this it might happen because github is not able to track their PR and contribution, it is by github only i can't do much in it.

**Comment by tarunkumar2005** [comment]
@notsoocool What can i do about this github is only sending 5 objects in response.

**Comment by notsoocool** [comment]
> @notsoocool What can i do about this github is only sending 5 objects in response.

No worries! I will go through it as soon as I have some free time. In the meantime, I'll merge your PR into a different branch. Thanks for your understanding!

**Comment by tarunkumar2005** [comment]
@notsoocool Thank you i will also look into it if i find anything to help then i will ping you here.

**Comment by tarunkumar2005** [comment]
@notsoocool Just asking to make it level 3 as the ui design is very good and it is responsive for all screen sizes so no need to work on this more right so it can be level 3.

**Comment by notsoocool** [comment]
@tarunkumar2005 I was initially assigning `level3` to PRs that involve API and model changes or modifications that affect both the APIs and models, including the page. However, since @sanjay-kv has already labeled your PR as level3, I won't change it for now. Just keep this information in mind for future contributions. Thanks!

**Pull request merged**
