### PR TITLE
My Snippets Page

### PR DESCRIPTION
**Pull request by inkerton**
I made the backend route named mysnippets/[id] to fetch the snippets submitted by the current user.
Along with the frontend with a useeffect to fetch current user and fetchUsersSnippets to fetch the snippets written by current user.

image

### CODE REVIEW

**Comment by inkerton** [comment]
@notsoocool  This is in response to the issue #34

**Comment by notsoocool** [comment]
@inkerton, I appreciate your contribution, but we need to make a few adjustments:

1. Kindly pull the latest changes from the `develop` branch, as we've introduced a new **My Profile** section when you click on your avatar. This section now includes **My Snippets**, **My Bookmarks**, and **My Contributions**.
2. What I'd like you to do is revamp the design of **My Snippets** section and make any necessary updates. Also, please check if the **My Snippets** feature is functioning properly.

Thank you!

**Comment by notsoocool** [comment]
Also please raise a PR for develop branch only!

**Comment by inkerton** [comment]
I don't see any  **My Profile section** . @notsoocool

**Comment by notsoocool** [comment]
> I don't see any **My Profile section** . @notsoocool I made a new branch on your develop branch

Screenshot 2024-10-08 at 4 20 05 PM


you will see it if you fetch the develop branch with the latest updates

**Pull request closed without merging**
