### PR TITLE
Rebuilt UI of home Page

### LINKED ISSUE #115: UI Improvement in Home Page
**Is your feature request related to a problem? Please describe.**
The Home page is not attractive , info should be present in an easily readable format

**Describe the solution you'd like**
The key features of the project can be presented in the form of cards rather than a bullet list. An image can be added to the front page to demonstrate the entire website. This will be accompanied by complete documentation, allowing us to make necessary changes to enhance its attractiveness and improve the user experience.

**Describe alternatives you've considered**
A bit of framer motion can be used

**Additional context**
Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.

### PR DESCRIPTION
**Pull request by Bhum-ika**
Fixed #115 

https://github.com/user-attachments/assets/d040f277-6de8-4c5e-a962-4627f3dc844f

I have made sure that it is responsive after certain changes.

If you really like the changes, please upgrade it to level 3.
I would really appreciate it

### CODE REVIEW

**Comment by notsoocool** [comment]
@Bhum-ika I'm really impressed with the changes you've made, especially how you've ensured responsiveness! I truly appreciate the effort you've put into this. Great work!.
I will review the code once and will merge it after.
Thank you for your contribution.

**Comment by Bhum-ika** [comment]
I am happy to know that you liked my contribution. 
After reviewing, if all goes well, please upgrade it to level 3
It would really boost up my confidence

**Comment by Bhum-ika** [comment]
I am happy to know that you liked my contribution. 
After reviewing, if all goes well, please upgrade it to level 3
It would really boost up my confidence

**Comment by notsoocool** [comment]
Since this is your first time contributing to this project, and you've successfully made a PR on your first attempt, I'll grant you `level3`. However, for future contributions to receive the `level3` label, you'll need to meet the following criteria: either use or edit the project's APIs and models, or create a new page using the APIs and models. Keep up the great work!

**Comment by Bhum-ika** [comment]
Thank you so much. 
Noted

**Pull request merged**
