### PR TITLE
added scroll progress bar

### LINKED ISSUE #137: Adding Scroll Progress Bar
@notsoocool 
I would like to add scroll progress bar
could you please assign it to me

### PR DESCRIPTION
**Pull request by AswaniBolisetti**
@notsoocool 
I have created scroll progress bar successfully #137 
Kindly check it out

https://github.com/user-attachments/assets/34779b2f-17b2-403c-a368-e9a5c0fb87d1

### CODE REVIEW

**Comment by notsoocool** [comment]
@AswaniBolisetti either kindly disable the default scrollbar, or make changes in the default scrollbar only.

**Comment by notsoocool** [comment]
@AswaniBolisetti this file has no other commit i will reopen it

**Comment by AswaniBolisetti** [comment]
@notsoocool 
Thanks for the clarification 
Let me tell you what happened from my end
I created scroll-progress first branch and made changes, created PR
Then I created enhance-footer branch, made changes and created PR
And I created terms-conditions branch , made changes and created PR

I thought it wouldn't be a problem even if we do like this, if the PR's are merged accordingly from the order they created 
Thanks again

**Comment by notsoocool** [comment]
> @AswaniBolisetti either kindly disable the default scrollbar, or make changes in the default scrollbar only.

For now just follow my steps to stop any further confusion. just do the specified changes and update me

**Comment by AswaniBolisetti** [comment]
@notsoocool 
What should I now

**Comment by notsoocool** [comment]
@AswaniBolisetti either kindly disable the default scrollbar, or make changes in the default scrollbar only.
Its not looking good, as there are two bars showing progress and scrolling

**Comment by AswaniBolisetti** [comment]
@notsoocool 
I have removed the default scroll progress
Kindly check it out


https://github.com/user-attachments/assets/0771fbb3-8ef7-409a-8508-b86f449df8a5

**Comment by AswaniBolisetti** [comment]
@notsoocool 
Kindly review it please

**Comment by AswaniBolisetti** [comment]
@notsoocool 
Could you please review and merge it

**Comment by notsoocool** [comment]
@AswaniBolisetti there is some error in your code, thats why I haven't merge it yet, i thought you already saw the error in deployment

**Comment by notsoocool** [comment]
Screenshot 2024-10-24 at 10 44 06 PM

**Comment by AswaniBolisetti** [comment]
@notsoocool 
Sorry I deleted this from my repos to fork again, i dont know that it will close this
If ok, I'll raise this again and work on it

**Pull request closed without merging**
