### PR TITLE
Added cursor animation to all pages 

### PR DESCRIPTION
**Pull request by KapuluruBhuvaneswariVspdbct**
Added cursor animation to all pages 
please add level3 if possible by considering my efforts

https://github.com/user-attachments/assets/bc15013d-2bf7-473e-85a3-0875a59c9ade

### CODE REVIEW

**Comment by notsoocool** [comment]
@KapuluruBhuvaneswariVspdbct, why are you calling the function on every page when you could call it just once on the layout page of the (dashboard)?

**Comment by notsoocool** [comment]
And instead of using a trailing cursor, could you try implementing a negative cursor effect?

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
ok i will

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
it is done sir 
please check out 

https://github.com/user-attachments/assets/d20a4e24-cebe-4ca3-be6b-be3ccb79d420

**Comment by notsoocool** [comment]
@KapuluruBhuvaneswariVspdbct as i have mentioned earlier revert all the files back where you have added the Trailingcursor function, and just mention it in the layout.

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
Ok

**Pull request closed without merging**
