### PR TITLE
add subscribe to the platform

### LINKED ISSUE #171: Add subscribe to our platform
**Is your feature request related to a problem? Please describe.**
I want to add subscribing feature to the application so that users filling in their email ids in the footer of the website receive a confirmation mail to their valid mail ids.
Users will receive the confirmation mail and a success toast will be shown on the website.

**Describe the solution you'd like**
I will create backend api for the mail sending purpose and also a frontend component where users can fill in their mail ids for subscription.

### PR DESCRIPTION
**Pull request by haseebzaki-07**
## fixes #171 

This PR adds the backend API for emailing service using nodemailer,
Created the frontend component for users to give in their mail ids,
Integrated both frontend and backend for the purpose and also added toast notifications for success and error alerts.

Screenshot 2024-10-28 133506

https://github.com/user-attachments/assets/f96fda7c-aa5d-4dc6-afde-ab9d6e19916a

WhatsApp Image 2024-10-28 at 3 10 15 PM

### CODE REVIEW

**Comment by haseebzaki-07** [comment]
hey @notsoocool done everything and extra toast addition, please increase the level of the PR

**Review by notsoocool — CHANGES_REQUESTED** [review]
I’d like you to make a few changes as noted previously on your issue:

1. **Subscribe Changes**: Kindly make any changes related to subscribing only on the contact us page, as there frontend is already ready only implementing the backend was left.
2. **Toast Notification**: Please use the default toast `sonner` instead of `react-toastify`.
3. **Environment Variables**: Specify any additional environment variables you've added.

Thank you!

**Comment by haseebzaki-07** [comment]
Sure @notsoocool I will make the changes

**Comment by haseebzaki-07** [comment]
@notsoocool I want to ask a thing, The contact us page is for users to contact the admin/maintainer of the website and their mails should be rolled out to the admin. 
Subscribing the platform in another thing, like newsletter or stay updated where users get only the confirmation mail and further mails for updates.

Contact us page can be implememented separately so that the users feedbacks are stored in the database and their responses are sent to their mail ids.

What  should I do??

**Comment by notsoocool** [comment]
> @notsoocool I want to ask a thing, The contact us page is for users to contact the admin/maintainer of the website and their mails should be rolled out to the admin. Subscribing the platform in another thing, like newsletter or stay updated where users get only the confirmation mail and further mails for updates.
> 
> Contact us page can be implememented separately so that the users feedbacks are stored in the database and their responses are sent to their mail ids.
> 
> What should I do??

I understand what you are trying to say, see i basically don't want anything included in the footer, you can either add it in the contact us page, faq page, my profile page, whatever suits you best, but no in the footer

**Comment by haseebzaki-07** [comment]
Okay I'll do it

**Comment by haseebzaki-07** [comment]
Screenshot 2024-10-28 172309
hey @notsoocool made the changes.

Brought sonner instead of react-toastify.
Changed the stay updated component from footer to contact us.
smtp_user and smtp_pass are the two fields in the .env file that are necessary for the email sending.

**Review by notsoocool — APPROVED** [review]

**Pull request merged**
