### PR TITLE
CursorAnimationDone

### PR DESCRIPTION
**Pull request by KapuluruBhuvaneswariVspdbct**
#174 solved

### CODE REVIEW

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
@notsoocool  sir please review this pull request

**Review by notsoocool — CHANGES_REQUESTED** [review]
Screenshot 2024-10-30 at 2 02 32 PM
kindly fix this issue

**Comment by notsoocool** [comment]
@KapuluruBhuvaneswariVspdbct any updates??

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
check the #199 pr
please

**Pull request closed without merging**
